name: Fetch EV Station Data

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes back
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your desired Node.js version
          cache: 'npm' # Optional: cache npm dependencies if you have any

      # Optional: Install dependencies if you have a package.json
      # - name: Install dependencies
      #   run: npm ci

      - name: Run Fetch Script and Commit Changes
        # Assumes the bash script is at this location
        run: .github/scripts/run_and_commit.sh
